# Generated by Django 3.2.4 on 2022-07-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=264)),
                ('text1', models.TextField(max_length=1000)),
                ('text2', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Client_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=264, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clients')),
            ],
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('subtitle', models.CharField(max_length=100)),
                ('shorttext', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='testimonials')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('text', models.TextField(max_length=500)),
                ('client_image', models.ManyToManyField(blank=True, to='about.Client_image')),
            ],
        ),
    ]
