# Generated by Django 3.2.4 on 2022-07-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Top_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_icon', models.ImageField(upload_to='')),
                ('fav_icon2', models.ImageField(upload_to='')),
                ('number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('linkedin', models.URLField()),
            ],
        ),
    ]
