# Generated by Django 3.2.4 on 2022-07-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Top_footer1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('urlname1', models.CharField(max_length=50)),
                ('urlname2', models.CharField(max_length=50)),
                ('urlname3', models.CharField(max_length=50)),
                ('urlname4', models.CharField(max_length=50)),
                ('urlname5', models.CharField(max_length=50)),
                ('url1', models.URLField(max_length=50)),
                ('url2', models.URLField(max_length=50)),
                ('url3', models.URLField(max_length=50)),
                ('url4', models.URLField(max_length=50)),
                ('url5', models.URLField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Top_footer2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('urlname1', models.CharField(max_length=50)),
                ('urlname2', models.CharField(max_length=50)),
                ('urlname3', models.CharField(max_length=50)),
                ('urlname4', models.CharField(max_length=50)),
                ('urlname5', models.CharField(max_length=50)),
                ('url1', models.URLField(max_length=50)),
                ('url2', models.URLField(max_length=50)),
                ('url3', models.URLField(max_length=50)),
                ('url4', models.URLField(max_length=50)),
                ('url5', models.URLField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Top_footer3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=30)),
                ('address2', models.CharField(max_length=30)),
                ('address3', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Top_footer4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('short_text', models.CharField(max_length=200)),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('linkedin', models.URLField()),
                ('skype', models.URLField()),
                ('copy_right', models.CharField(max_length=30)),
            ],
        ),
    ]
