# Generated by Django 3.2.4 on 2022-10-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Top_footer1',
        ),
        migrations.DeleteModel(
            name='Top_footer2',
        ),
        migrations.DeleteModel(
            name='Top_footer3',
        ),
        migrations.DeleteModel(
            name='Top_footer4',
        ),
    ]
